# Generated by Django 5.0.6 on 2024-06-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardumen',
            fields=[
                ('especie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('profundidad_min', models.IntegerField()),
                ('profundidad_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('x_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('y_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('es_viaje_exitoso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('y_max', models.IntegerField()),
                ('profundidad', models.IntegerField()),
                ('temperatura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViajeCardumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminBD.cardumen')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminBD.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='viaje',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminBD.zona'),
        ),
    ]
