# Generated by Django 5.0.6 on 2024-06-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='zona',
            new_name='zona_id',
        ),
        migrations.RenameField(
            model_name='viajecardumen',
            old_name='viaje',
            new_name='viaje_id',
        ),
    ]
