# Generated by Django 5.0.6 on 2024-05-10 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadaX', models.IntegerField()),
                ('coordenadaY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardumen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminBD.cardumen')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminBD.zona')),
            ],
        ),
    ]
