# Generated by Django 5.0.6 on 2024-05-10 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0002_zona_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='cardumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminBD.cardumen'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminBD.zona'),
        ),
    ]
