# Generated by Django 5.0.6 on 2024-06-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0002_rename_zona_viaje_zona_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viajecardumen',
            old_name='cardumen',
            new_name='cardumen_especie',
        ),
    ]
