# Generated by Django 5.0.6 on 2024-06-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0003_rename_cardumen_viajecardumen_cardumen_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='zona_id',
            new_name='zona',
        ),
        migrations.RenameField(
            model_name='viajecardumen',
            old_name='cardumen_especie',
            new_name='cardumen',
        ),
        migrations.RenameField(
            model_name='viajecardumen',
            old_name='viaje_id',
            new_name='viaje',
        ),
    ]
