# Generated by Django 5.0.6 on 2024-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0004_remove_cardumen_id_alter_cardumen_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitat',
            name='composite_primary_key',
        ),
        migrations.AddConstraint(
            model_name='habitat',
            constraint=models.UniqueConstraint(fields=('cardumen', 'zona'), name='habitat_key'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('coordenadaX', 'coordenadaY'), name='zona_key'),
        ),
    ]
