# Generated by Django 5.0.6 on 2024-05-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminBD', '0005_remove_habitat_composite_primary_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='cardumen',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='zona',
        ),
        migrations.DeleteModel(
            name='cardumen',
        ),
        migrations.DeleteModel(
            name='habitat',
        ),
        migrations.DeleteModel(
            name='zona',
        ),
    ]
