# Generated by Django 5.0.6 on 2024-05-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminBD', '0006_remove_habitat_cardumen_remove_habitat_zona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardumen',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadaX', models.IntegerField()),
                ('coordenadaY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardumen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminBD.cardumen')),
            ],
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('coordenadaX', 'coordenadaY'), name='zona_key'),
        ),
        migrations.AddField(
            model_name='habitat',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminBD.zona'),
        ),
        migrations.AddConstraint(
            model_name='habitat',
            constraint=models.UniqueConstraint(fields=('cardumen', 'zona'), name='habitat_key'),
        ),
    ]
